// <auto-generated />
using System;
using ArbinInsight.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArbinInsight.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260327084803_AddDashboardReporting")]
    partial class AddDashboardReporting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArbinInsight.Models.CANMessagePair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BrokerReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChannelId")
                        .HasColumnType("int");

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PublisherNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SourceLocalId")
                        .HasColumnType("int");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("CANMessagePairs");
                });

            modelBuilder.Entity("ArbinInsight.Models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BINNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BrokerReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("ChannelIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MachineDataId")
                        .HasColumnType("int");

                    b.Property<bool>("ManuallyStopFlag")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PublisherNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Retest")
                        .HasColumnType("bit");

                    b.Property<string>("RetestNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceLocalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("StopTestsExecuted")
                        .HasColumnType("bit");

                    b.Property<int>("TestID")
                        .HasColumnType("int");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestProfileId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ambientTemperature")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("TestProfileId");

                    b.HasIndex("MachineDataId", "ChannelIndex")
                        .IsUnique()
                        .HasFilter("[MachineDataId] IS NOT NULL");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("ArbinInsight.Models.ChannelStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<float?>("AmbientTemperature")
                        .HasColumnType("real");

                    b.Property<string>("BINNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<long>("ChannelIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("bit");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PublisherNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SnapshotAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "SnapshotAtUtc");

                    b.HasIndex("PublisherNodeId", "ChannelIndex", "SnapshotAtUtc");

                    b.ToTable("ChannelStatusHistory", (string)null);
                });

            modelBuilder.Entity("ArbinInsight.Models.Limit", b =>
                {
                    b.Property<int>("LimitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LimitID"));

                    b.Property<DateTime?>("BrokerReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LimitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaxValue")
                        .HasColumnType("float");

                    b.Property<string>("MeasuredValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MinValue")
                        .HasColumnType("float");

                    b.Property<Guid?>("PublisherNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceLocalId")
                        .HasColumnType("int");

                    b.Property<int?>("TestId")
                        .HasColumnType("int");

                    b.Property<string>("Tolerance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LimitID");

                    b.HasIndex("TestId");

                    b.HasIndex("PublisherNodeId", "SourceLocalId")
                        .IsUnique()
                        .HasFilter("[PublisherNodeId] IS NOT NULL AND [SourceLocalId] IS NOT NULL");

                    b.ToTable("Limit", (string)null);
                });

            modelBuilder.Entity("ArbinInsight.Models.MachineData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BrokerReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("Capacity")
                        .HasColumnType("float");

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PublisherNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SourceLocalId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublisherNodeId", "MachineId")
                        .IsUnique()
                        .HasFilter("[PublisherNodeId] IS NOT NULL");

                    b.ToTable("MachineDatas");
                });

            modelBuilder.Entity("ArbinInsight.Models.MachineStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double?>("Capacity")
                        .HasColumnType("float");

                    b.Property<int>("MachineDataId")
                        .HasColumnType("int");

                    b.Property<string>("MachineStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PublisherNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SnapshotAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MachineDataId", "SnapshotAtUtc");

                    b.ToTable("MachineStatusHistory", (string)null);
                });

            modelBuilder.Entity("ArbinInsight.Models.Reporting.DashboardLimitRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("DashboardSubTestRunId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DashboardTestRunId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LastMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LimitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("float");

                    b.Property<string>("MeasuredValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MinValue")
                        .HasColumnType("float");

                    b.Property<string>("ParentSourceSubTestKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentSourceTestKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceConnectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SourceLimitKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tolerance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DashboardTestRunId");

                    b.HasIndex("DashboardSubTestRunId", "LastSyncedAtUtc");

                    b.HasIndex("SourceConnectionName", "SourceLimitKey")
                        .IsUnique();

                    b.ToTable("DashboardLimitRecords", "reporting");
                });

            modelBuilder.Entity("ArbinInsight.Models.Reporting.DashboardSubTestRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DashboardTestRunId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Enable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EndDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParentSourceTestKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceConnectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SourceSubTestKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("StartDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("StopOnFail")
                        .HasColumnType("bit");

                    b.Property<string>("TestName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DashboardTestRunId", "LastSyncedAtUtc");

                    b.HasIndex("SourceConnectionName", "SourceSubTestKey")
                        .IsUnique();

                    b.ToTable("DashboardSubTestRuns", "reporting");
                });

            modelBuilder.Entity("ArbinInsight.Models.Reporting.DashboardTestRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BinNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChannelIndex")
                        .HasColumnType("int");

                    b.Property<long?>("EndDateTimeRaw")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublisherNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Retest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceConnectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SourceTestKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("StartDateTimeRaw")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestProfileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublisherNodeId", "LastSyncedAtUtc");

                    b.HasIndex("SourceConnectionName", "SourceTestKey")
                        .IsUnique();

                    b.ToTable("DashboardTestRuns", "reporting");
                });

            modelBuilder.Entity("ArbinInsight.Models.SMBMessagePair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BrokerReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChannelId")
                        .HasColumnType("int");

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PublisherNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SourceLocalId")
                        .HasColumnType("int");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("SMBMessagePair");
                });

            modelBuilder.Entity("ArbinInsight.Models.Sync.DeadLetterMessage", b =>
                {
                    b.Property<long>("DeadLetterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DeadLetterId"));

                    b.Property<string>("ErrorText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FailedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublisherNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeadLetterId");

                    b.ToTable("DeadLetterMessages", "sync");
                });

            modelBuilder.Entity("ArbinInsight.Models.Sync.InboxMessage", b =>
                {
                    b.Property<long>("InboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InboxId"));

                    b.Property<string>("ErrorText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PublisherNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.HasKey("InboxId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("Status", "ReceivedAtUtc");

                    b.ToTable("InboxMessages", "sync");
                });

            modelBuilder.Entity("ArbinInsight.Models.Sync.MachineHeartbeat", b =>
                {
                    b.Property<long>("HeartbeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HeartbeatId"));

                    b.Property<string>("MachineStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublisherNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("QueueDepth")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("HeartbeatId");

                    b.ToTable("MachineHeartbeats", "sync");
                });

            modelBuilder.Entity("ArbinInsight.Models.Sync.OutboxMessage", b =>
                {
                    b.Property<long>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OutboxId"));

                    b.Property<string>("AggregateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AggregateType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PublisherNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.HasKey("OutboxId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("Status", "NextRetryAtUtc");

                    b.ToTable("OutboxMessages", "sync");
                });

            modelBuilder.Entity("ArbinInsight.Models.Sync.PublisherNode", b =>
                {
                    b.Property<Guid>("PublisherNodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("HostName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastHeartbeatUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NodeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("PublisherNodeId");

                    b.HasIndex("NodeCode")
                        .IsUnique();

                    b.ToTable("PublisherNodes", "sync");
                });

            modelBuilder.Entity("ArbinInsight.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BrokerReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChannelId")
                        .HasColumnType("int");

                    b.Property<bool>("Enable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PublisherNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceLocalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("StopOnFail")
                        .HasColumnType("bit");

                    b.Property<int>("TestID")
                        .HasColumnType("int");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TestProfileId")
                        .HasColumnType("int");

                    b.Property<string>("TestStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("TestProfileId");

                    b.HasIndex("PublisherNodeId", "SourceLocalId")
                        .IsUnique()
                        .HasFilter("[PublisherNodeId] IS NOT NULL AND [SourceLocalId] IS NOT NULL");

                    b.ToTable("Test", (string)null);
                });

            modelBuilder.Entity("ArbinInsight.Models.TestList", b =>
                {
                    b.Property<int>("Test_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Test_ID"));

                    b.Property<string>("BIN_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BrokerReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChannelId")
                        .HasColumnType("int");

                    b.Property<int?>("Channel_Index")
                        .HasColumnType("int");

                    b.Property<long?>("End_Date_Time")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MachineDataId")
                        .HasColumnType("int");

                    b.Property<Guid?>("PublisherNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Retest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceLocalId")
                        .HasColumnType("int");

                    b.Property<long?>("Start_Date_Time")
                        .HasColumnType("bigint");

                    b.Property<int?>("TestProfileId")
                        .HasColumnType("int");

                    b.Property<string>("TestProfile_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Test_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Test_ID");

                    b.HasIndex("ChannelId");

                    b.HasIndex("TestProfileId");

                    b.HasIndex("PublisherNodeId", "SourceLocalId")
                        .IsUnique()
                        .HasFilter("[PublisherNodeId] IS NOT NULL AND [SourceLocalId] IS NOT NULL");

                    b.HasIndex("MachineDataId", "ChannelId", "Start_Date_Time");

                    b.ToTable("TestList_Table");
                });

            modelBuilder.Entity("ArbinInsight.Models.TestProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BrokerReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CANBMSFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExecuteStopTests")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PublisherNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SMBFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceLocalId")
                        .HasColumnType("int");

                    b.Property<string>("TestObjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestProfileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDSRequestID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDSResponseID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublisherNodeId", "SourceLocalId")
                        .IsUnique()
                        .HasFilter("[PublisherNodeId] IS NOT NULL AND [SourceLocalId] IS NOT NULL");

                    b.ToTable("TestProfiles");
                });

            modelBuilder.Entity("ArbinInsight.Models.CANMessagePair", b =>
                {
                    b.HasOne("ArbinInsight.Models.Channel", "Channel")
                        .WithMany("cANMessagePairList")
                        .HasForeignKey("ChannelId");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("ArbinInsight.Models.Channel", b =>
                {
                    b.HasOne("ArbinInsight.Models.MachineData", "MachineData")
                        .WithMany("Channels")
                        .HasForeignKey("MachineDataId");

                    b.HasOne("ArbinInsight.Models.TestProfile", "testProfile")
                        .WithMany()
                        .HasForeignKey("TestProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineData");

                    b.Navigation("testProfile");
                });

            modelBuilder.Entity("ArbinInsight.Models.ChannelStatusHistory", b =>
                {
                    b.HasOne("ArbinInsight.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("ArbinInsight.Models.Limit", b =>
                {
                    b.HasOne("ArbinInsight.Models.Test", "Test")
                        .WithMany("Limits")
                        .HasForeignKey("TestId");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("ArbinInsight.Models.MachineStatusHistory", b =>
                {
                    b.HasOne("ArbinInsight.Models.MachineData", "MachineData")
                        .WithMany()
                        .HasForeignKey("MachineDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineData");
                });

            modelBuilder.Entity("ArbinInsight.Models.Reporting.DashboardLimitRecord", b =>
                {
                    b.HasOne("ArbinInsight.Models.Reporting.DashboardSubTestRun", "DashboardSubTestRun")
                        .WithMany("Limits")
                        .HasForeignKey("DashboardSubTestRunId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ArbinInsight.Models.Reporting.DashboardTestRun", "DashboardTestRun")
                        .WithMany("Limits")
                        .HasForeignKey("DashboardTestRunId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DashboardSubTestRun");

                    b.Navigation("DashboardTestRun");
                });

            modelBuilder.Entity("ArbinInsight.Models.Reporting.DashboardSubTestRun", b =>
                {
                    b.HasOne("ArbinInsight.Models.Reporting.DashboardTestRun", "DashboardTestRun")
                        .WithMany("SubTests")
                        .HasForeignKey("DashboardTestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DashboardTestRun");
                });

            modelBuilder.Entity("ArbinInsight.Models.SMBMessagePair", b =>
                {
                    b.HasOne("ArbinInsight.Models.Channel", "Channel")
                        .WithMany("sMBMessagePairList")
                        .HasForeignKey("ChannelId");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("ArbinInsight.Models.Test", b =>
                {
                    b.HasOne("ArbinInsight.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ArbinInsight.Models.TestProfile", null)
                        .WithMany("Tests")
                        .HasForeignKey("TestProfileId");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("ArbinInsight.Models.TestList", b =>
                {
                    b.HasOne("ArbinInsight.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ArbinInsight.Models.MachineData", "MachineData")
                        .WithMany("TestLists")
                        .HasForeignKey("MachineDataId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ArbinInsight.Models.TestProfile", "TestProfile")
                        .WithMany()
                        .HasForeignKey("TestProfileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Channel");

                    b.Navigation("MachineData");

                    b.Navigation("TestProfile");
                });

            modelBuilder.Entity("ArbinInsight.Models.Channel", b =>
                {
                    b.Navigation("cANMessagePairList");

                    b.Navigation("sMBMessagePairList");
                });

            modelBuilder.Entity("ArbinInsight.Models.MachineData", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("TestLists");
                });

            modelBuilder.Entity("ArbinInsight.Models.Reporting.DashboardSubTestRun", b =>
                {
                    b.Navigation("Limits");
                });

            modelBuilder.Entity("ArbinInsight.Models.Reporting.DashboardTestRun", b =>
                {
                    b.Navigation("Limits");

                    b.Navigation("SubTests");
                });

            modelBuilder.Entity("ArbinInsight.Models.Test", b =>
                {
                    b.Navigation("Limits");
                });

            modelBuilder.Entity("ArbinInsight.Models.TestProfile", b =>
                {
                    b.Navigation("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
