// <auto-generated />
using System;
using ArbinInsight.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArbinInsight.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326091940_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArbinInsight.Models.CANMessagePair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChannelId")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("CANMessagePairs");
                });

            modelBuilder.Entity("ArbinInsight.Models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BINNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ChannelIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("bit");

                    b.Property<int?>("MachineDataId")
                        .HasColumnType("int");

                    b.Property<bool>("ManuallyStopFlag")
                        .HasColumnType("bit");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Retest")
                        .HasColumnType("bit");

                    b.Property<string>("RetestNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("StopTestsExecuted")
                        .HasColumnType("bit");

                    b.Property<int>("TestID")
                        .HasColumnType("int");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ambientTemperature")
                        .HasColumnType("real");

                    b.Property<int>("testProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineDataId");

                    b.HasIndex("testProfileId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("ArbinInsight.Models.Limit", b =>
                {
                    b.Property<int>("LimitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LimitID"));

                    b.Property<string>("LimitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaxValue")
                        .HasColumnType("float");

                    b.Property<string>("MeasuredValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MinValue")
                        .HasColumnType("float");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TestId")
                        .HasColumnType("int");

                    b.Property<string>("Tolerance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LimitID");

                    b.HasIndex("TestId");

                    b.ToTable("Limit");
                });

            modelBuilder.Entity("ArbinInsight.Models.MachineData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Capacity")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MachineDatas");
                });

            modelBuilder.Entity("ArbinInsight.Models.SMBMessagePair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChannelId")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("SMBMessagePair");
                });

            modelBuilder.Entity("ArbinInsight.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("StopOnFail")
                        .HasColumnType("bit");

                    b.Property<int>("TestID")
                        .HasColumnType("int");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TestProfileId")
                        .HasColumnType("int");

                    b.Property<string>("TestStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TestProfileId");

                    b.ToTable("Test");
                });

            modelBuilder.Entity("ArbinInsight.Models.TestList", b =>
                {
                    b.Property<int>("Test_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Test_ID"));

                    b.Property<string>("BIN_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Channel_Index")
                        .HasColumnType("int");

                    b.Property<long?>("End_Date_Time")
                        .HasColumnType("bigint");

                    b.Property<int?>("MachineDataId")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Retest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Start_Date_Time")
                        .HasColumnType("bigint");

                    b.Property<string>("TestProfile_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Test_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Test_ID");

                    b.HasIndex("MachineDataId");

                    b.ToTable("TestList_Table");
                });

            modelBuilder.Entity("ArbinInsight.Models.TestProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CANBMSFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExecuteStopTests")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SMBFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestObjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestProfileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDSRequestID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDSResponseID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TestProfiles");
                });

            modelBuilder.Entity("ArbinInsight.Models.CANMessagePair", b =>
                {
                    b.HasOne("ArbinInsight.Models.Channel", null)
                        .WithMany("cANMessagePairList")
                        .HasForeignKey("ChannelId");
                });

            modelBuilder.Entity("ArbinInsight.Models.Channel", b =>
                {
                    b.HasOne("ArbinInsight.Models.MachineData", null)
                        .WithMany("Channels")
                        .HasForeignKey("MachineDataId");

                    b.HasOne("ArbinInsight.Models.TestProfile", "testProfile")
                        .WithMany()
                        .HasForeignKey("testProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("testProfile");
                });

            modelBuilder.Entity("ArbinInsight.Models.Limit", b =>
                {
                    b.HasOne("ArbinInsight.Models.Test", null)
                        .WithMany("Limits")
                        .HasForeignKey("TestId");
                });

            modelBuilder.Entity("ArbinInsight.Models.SMBMessagePair", b =>
                {
                    b.HasOne("ArbinInsight.Models.Channel", null)
                        .WithMany("sMBMessagePairList")
                        .HasForeignKey("ChannelId");
                });

            modelBuilder.Entity("ArbinInsight.Models.Test", b =>
                {
                    b.HasOne("ArbinInsight.Models.TestProfile", null)
                        .WithMany("Tests")
                        .HasForeignKey("TestProfileId");
                });

            modelBuilder.Entity("ArbinInsight.Models.TestList", b =>
                {
                    b.HasOne("ArbinInsight.Models.MachineData", "MachineData")
                        .WithMany()
                        .HasForeignKey("MachineDataId");

                    b.Navigation("MachineData");
                });

            modelBuilder.Entity("ArbinInsight.Models.Channel", b =>
                {
                    b.Navigation("cANMessagePairList");

                    b.Navigation("sMBMessagePairList");
                });

            modelBuilder.Entity("ArbinInsight.Models.MachineData", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("ArbinInsight.Models.Test", b =>
                {
                    b.Navigation("Limits");
                });

            modelBuilder.Entity("ArbinInsight.Models.TestProfile", b =>
                {
                    b.Navigation("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
